name: Manual Release

on:
  workflow_dispatch:
    inputs:
      version_bump:
        description: "Version bump type"
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.jkpy_semvar_token }}

      - name: Set up python
        uses: actions/setup-python@v5
        with: 
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install python-semantic-release

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Semantic Release
        env:
          GH_TOKEN: ${{ secrets.jkpy_semvar_token }}
        run: |
          semantic-release version --${{ github.event.inputs.version_bump }}
          semantic-release publish